<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Home" ignored="0" name="Test" tests="5" failures="2" timestamp="02 Oct 2018 07:43:00 GMT" time="14.085" errors="0">
  <testcase name="testMyObjectToString" time="0.007" classname="automationTest.com.automation.test.trials.Grouping">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at automationTest.com.automation.test.trials.Grouping.testMyObjectToString(Grouping.java:21)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testMyObjectToString -->
  <testcase name="TC2" time="0.003" classname="automationTest.com.automation.test.trials.DependsOnMethods"/>
  <testcase name="TC1" time="0.007" classname="automationTest.com.automation.test.trials.DependsOnMethods"/>
  <testcase name="LoginPage" time="13.958" classname="automationTest.com.automation.test.trials.TestCaseLoginForListeners"/>
  <testcase name="LoginPageForciblyFail" time="0.011" classname="automationTest.com.automation.test.trials.TestCaseLoginForListeners">
    <failure type="java.lang.AssertionError" message="expected [14] but found [12]">
      <![CDATA[java.lang.AssertionError: expected [14] but found [12]
at automationTest.com.automation.test.trials.TestCaseLoginForListeners.LoginPageForciblyFail(TestCaseLoginForListeners.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginPageForciblyFail -->
</testsuite> <!-- Test -->
